site_author: Ampify Authors
site_description:
    Ampify is a vision of a better future. Help it happen with £10/month. Open
    Source + Reputation Economy = Web 4.0

site_license: This work has been placed into the Public Domain.
site_title: "Support Ampify: Create Weapons of Mass Construction!"
site_url: http://ampify.it

analytics_id: UA-90176-24
section_id: about

index_pages:
- bank-transfer.html: bank-transfer.genshi
- community.html: community.genshi
- index.html: index.genshi
