application: tentapp
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 1d

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: 1d

- url: /static
  static_dir: static
  expiration: 7d
  secure: always

- url: .*
  script: tentapp.py
  secure: always