application: zerodata
version: 1
runtime: python
api_version: 1

handlers:

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: 7d
  secure: optional

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 7d
  secure: optional

- url: /.remote/.*
  script: remote.py
  secure: always

- url: .*
  script: zerodata.py
  secure: always
