# No Copyright (-) 2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

repo_id: ampify
upstream_repo: https://github.com/tav/ampify.git
gitreview_repo: https://github.com/gitreview/ampify.git
default_branch: master
review_server: http://localhost:8090
cc: ampify@googlegroups.com
watchlist: on

slave:
- ['py-tests', './environ/amp', 'test', 'python']
- ['go-tests', './environ/amp', 'test', 'go']
