# Public Domain (-) 2010-2011 The Ampify Authors.
# See the UNLICENSE file for details.

repo_id: ampify
upstream_repo: https://github.com/tav/ampify.git
gitreview_repo: https://github.com/gitreview/ampify.git
default_branch: master
review_server: http://gitreview.com
cc: ampify-review@googlegroups.com
watchlist: on

slave:
- ['init', './environ/amp', 'build']
- ['py-tests', './environ/amp', 'test', 'python']
- ['go-tests', './environ/amp', 'test', 'go']
- ['js-tests', './environ/amp', 'test', 'js']
