application: ampifyit
version: 1
runtime: python
api_version: 1

handlers:

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  expiration: 7d
  secure: optional

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  expiration: 7d
  secure: optional

- url: /remote/.*
  script: remote.py
  secure: always

- url: .*
  script: zerodata.py
  secure: always
