application: ampifyit
version: 1
runtime: python
api_version: 1

handlers:

- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml
  secure: optional

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: optional

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: 1d
  secure: optional

- url: /.static
  static_dir: static
  secure: optional

- url: /.remote/.*
  script: remote.py
  secure: always

- url: .*
  script: weblite.py
  secure: optional
